name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: init
      run: make init

    - name: configure
      run: make configure PLATFORM=broadcom

    - name: Install dependencies
      run: make SONIC_BUILD_JOBS=4 all
