name: Build PLATFORM=broadcom

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 720
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
        fetch-tags: true
    - name: Init
      run: make init

    - name: Configure PLATFORM
      run: make http_proxy='http://s-r815.otfs:3142' configure PLATFORM=broadcom
    
    - name: Make
      run: make SONIC_BUILD_JOBS=$(nproc) SONIC_DPKG_CACHE_METHOD=cache SONIC_DPKG_CACHE_SOURCE=/data/sonic-runner/_cache SONIC_VERSION_CACHE_METHOD=cache http_proxy='http://s-r815.otfs:3142' target/sonic-broadcom.bin

    - name: Copy target
      run: rsync -a --stats --delete target/ /data/sonic-target/

#    - name: 'Upload Artifact'
#      uses: actions/upload-artifact@v4
#      with:
#        name: sonic-broadcom.bin
#        path: target/sonic-broadcom.bin
